harvester/urls.py
from django.urls import path
from . import views

app_name = "harvester"

urlpatterns = [
    path('', views.index, name='index'),
    path('sources/', views.sources, name='sources'),
    path('sources/add/', views.add_source, name='add_source'),
    path('sources/<int:id>/', views.source, name='source'),
    path('sources/<int:id>/change', views.change_source, name='change_source'),
    path('sources/<int:id>/delete', views.delete_source, name='delete_source'),
    path('sources/<int:source_id>/records', views.records, name='records'),
    path('sources/<int:source_id>/collect_source', views.collect_source, name='collect_source'),
    path('sources/<int:source_id>/harvesting_status', views.harvesting_status, name='harvesting_status'),
    path('sources/<int:source_id>/files/add', views.add_source_file, name='add_source_file'),
    path('sources/<int:source_id>/files/<int:id>', views.source_file, name='source_file'),
    path('sources/<int:source_id>/files/<int:id>/change', views.change_source_file, name='change_source_file'),
    path('sources/<int:source_id>/files/<int:id>/delete', views.delete_source_file, name='delete_source_file'),
    path(
        'sources/<int:source_id>/files/<int:id>/calculate_records_count',
        views.calculate_records_count,
        name='calculate_records_count'
    ),
    path(
        'sources/<int:source_id>/files/<int:id>/testing',
        views.source_file_testing,
        name='source_file_testing'
    ),

    path('indexing_rules/', views.indexing_rules, name='indexing_rules'),
    path('indexing_rules/add', views.add_indexing_rules, name='add_indexing_rules'),
    path('indexing_rules/<int:id>/change', views.change_indexing_rules, name='change_indexing_rules'),
    path('indexing_rules/<int:id>/invoke', views.invoke_indexing_rule, name='invoke_indexing_rule'),
]

harvesting/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('harvester/', include('harvester.urls'))
]

harvester/forms.py
from django import forms
from . import models

POSITION_TYPE_CHOICES = (
    ('index', 'Порядковый номер'),
    ('offset', 'Позиция в файле'),
)

VIEW_CHOICES = (
    ('html', 'HTML'),
    ('text', 'Текст')
)


class SourceForm(forms.ModelForm):
    class Meta:
        model = models.Source
        exclude = []


class SourceFileForm(forms.ModelForm):
    class Meta:
        model = models.SourceRecordsFile
        exclude = ['source']


class IndexingRuleForm(forms.ModelForm):
    class Meta:
        model = models.IndexingRule
        exclude = []


class SourceFileTestingForm(forms.Form):
    position_type = forms.ChoiceField(
        label='Тип позиции',
        choices=POSITION_TYPE_CHOICES,
        initial=POSITION_TYPE_CHOICES[0][0],
        required=False
    )
    position = forms.IntegerField(
        label='Позиция',
        initial=0,
        required=False
    )
    view = forms.ChoiceField(
        label='Представление',
        choices=VIEW_CHOICES,
        initial=POSITION_TYPE_CHOICES[0][0],
        required=False
    )

harvester/views.py
# -*- coding: utf-8 -*-
import json
from django.core.paginator import Paginator
from django.db.transaction import atomic
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from . import forms
from . import models


@login_required
@atomic
def index(request):
    return render(request, 'harvester/index.html')


@login_required
@atomic
def sources(request):
    sources = models.Source.objects.all()

    return render(request, 'harvester/sources.html', {
        'sources': sources,
    })


@login_required
@atomic
def source(request, id):
    source = get_object_or_404(models.Source, id=id)
    source_records_files = models.SourceRecordsFile.objects.filter(source=source)
    return render(request, 'harvester/source.html', {
        'source': source,
        'source_records_files': source_records_files,
    })


@login_required
@atomic
def add_source(request):
    if request.method == 'POST':
        form = forms.SourceForm(request.POST)
        if form.is_valid():
            source = form.save(commit=False)
            source.save()
            return redirect('harvester:source', id=source.id)
    else:
        form = forms.SourceForm()
    return render(request, 'harvester/source_form.html', {
        'form': form,
    })


@login_required
@atomic
def change_source(request, id):
    source = get_object_or_404(models.Source, id=id)
    if request.method == 'POST':
        form = forms.SourceForm(request.POST, instance=source)
        if form.is_valid():
            form.save()
            return redirect('harvester:source', id=id)
    else:
        form = forms.SourceForm(instance=source)
    return render(request, 'harvester/source_form.html', {
        'form': form,
        'source': source
    })


@login_required
@atomic
def delete_source(request, id):
    source = get_object_or_404(models.Source, id=id)
    source.delete()
    return redirect('harvester:sources')


@login_required
@atomic
def source_file(request, source_id, id):
    source = get_object_or_404(models.Source, id=source_id)
    source_records_file = get_object_or_404(models.SourceRecordsFile, source=source, id=id)
    return render(request, 'harvester/source_file.html', {
        'source': source,
        'source_records_file': source_records_file,
    })


@login_required
@atomic
def add_source_file(request, source_id):
    source = get_object_or_404(models.Source, id=source_id)
    if request.method == 'POST':
        form = forms.SourceFileForm(request.POST)
        if form.is_valid():
            source_file = form.save(commit=False)
            source_file.source = source
            source_file.save()
            return redirect('harvester:source', id=source.id)
    else:
        form = forms.SourceFileForm()
    return render(request, 'harvester/source_file_form.html', {
        'source': source,
        'form': form,
    })


@login_required
@atomic
def change_source_file(request, source_id, id):
    source = get_object_or_404(models.Source, id=source_id)
    source_file = get_object_or_404(models.SourceRecordsFile, source=source, id=id)
    if request.method == 'POST':
        form = forms.SourceFileForm(request.POST, instance=source_file)
        if form.is_valid():
            source_file = form.save(commit=False)
            source_file.source = source
            source_file.save()
            return redirect('harvester:source_file', source_id=source.id, id=id)
    else:
        form = forms.SourceFileForm(instance=source_file)
    return render(request, 'harvester/source_file_form.html', {
        'source': source,
        'form': form,
        'source_file': source_file,
    })


@login_required
@atomic
def delete_source_file(request, source_id, id):
    source = get_object_or_404(models.Source, id=source_id)
    source_file = get_object_or_404(models.SourceRecordsFile, source=source, id=id)
    source_file.delete()
    return redirect('harvester:source', id=source.id)


@login_required
@atomic
def records(request, source_id):
    source = get_object_or_404(models.Source, id=source_id)
    records_list = models.Record.objects.filter(source=source)
    paginator = Paginator(records_list, 25)  # Show 25 contacts per page

    page = request.GET.get('page')
    records = paginator.get_page(page)
    return render(request, 'harvester/records.html', {
        'records': records,
        'source': source,
    })


@login_required
@atomic
def collect_source(request, source_id):
    source = get_object_or_404(models.Source, id=source_id)
    models.collect_source(source)
    return redirect('harvester:records', source_id=source_id)


@login_required
@atomic
def harvesting_status(request, source_id):
    source = get_object_or_404(models.Source, id=source_id)
    harvesting_status_list = models.HarvestingStatus.objects.filter(source=source).order_by('-create_date')
    return render(request, 'harvester/harvesting_status_list.html', {
        'harvesting_status_list': harvesting_status_list,
        'source': source,
    })


@login_required
@atomic
def indexing_rules(request):
    indexing_rules = models.IndexingRule.objects.all()
    return render(request, 'harvester/indexing_rules.html', {
        'indexing_rules': indexing_rules
    })


@login_required
@atomic
def add_indexing_rules(request):
    if request.method == 'POST':
        form = forms.IndexingRuleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('harvester:indexing_rules')
    else:
        form = forms.IndexingRuleForm()
    return render(request, 'harvester/indexing_rule_form.html', {
        'form': form
    })


@login_required
@atomic
def change_indexing_rules(request, id):
    indexing_rule = get_object_or_404(models.IndexingRule, id=id)
    if request.method == 'POST':
        form = forms.IndexingRuleForm(request.POST, instance=indexing_rule)
        if form.is_valid():
            form.save()
            return redirect('harvester:indexing_rules')
    else:
        form = forms.IndexingRuleForm(instance=indexing_rule)
    return render(request, 'harvester/indexing_rule_form.html', {
        'form': form
    })


@login_required
@atomic
def invoke_indexing_rule(request, id):
    indexing_rule = get_object_or_404(models.IndexingRule, id=id)
    indexing_document = {}
    # d = dict(locals(), **globals())
    c = compile(indexing_rule.content.strip(), 'My Code', 'exec')
    res = exec(c)
    print(indexing_document)
    return redirect('harvester:indexing_rules')


@login_required
@atomic
def calculate_records_count(request, source_id, id):
    source = get_object_or_404(models.Source, id=source_id)
    source_records_file = get_object_or_404(models.SourceRecordsFile, source=source, id=id)
    records_count = source_records_file.calculate_records_count()
    return HttpResponse(json.dumps({
        'result': records_count,
    }, ensure_ascii=False), content_type='application/json')


@login_required
@atomic
def source_file_testing(request, source_id, id):
    source = get_object_or_404(models.Source, id=source_id)
    source_records_file = get_object_or_404(models.SourceRecordsFile, source=source, id=id)

    position_type = 'index'
    position = 0
    view = 'html'

    testing_form = forms.SourceFileTestingForm(request.GET)
    if testing_form.is_valid():
        position_type = testing_form.cleaned_data['position_type'] or position_type
        position = testing_form.cleaned_data['position'] or position
        view = testing_form.cleaned_data['view'] or view

    record_dump = source_records_file.record_content(
        position_type=position_type,
        position=position,
        view=view,
    )

    return render(request, 'harvester/source_file_testing.html', {
        'source': source,
        'source_records_file': source_records_file,
        'record_dump': record_dump,
        'testing_form': testing_form,
    })

harvester/templates/harvester/harvesting_status_list.html
{% extends 'harvester/index.html' %}
{% load bootstrap3 %}
{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'harvester:sources' %}">Источники</a></li>
    <li><a href="{% url 'harvester:source' source.id %}">{{ source.name }} ({{ source.code }})</a></li>
    <li class="active">Журнла сбора</li>
{% endblock %}
{% block content %}
    <table class="table">
        <tr>
            <th>#</th>
            <th>Дата сбора</th>
{#            <th>Формат</th>#}
{#            <th>Схема</th>#}
{#            <th>Кодировка</th>#}
{#            <th>Размер (Мб)</th>#}
{#            <th>Статус</th>#}
            <th>Создано</th>
            <th>Обновлено</th>
            <th>Удалено</th>
            <th>Всего обработано</th>
            <th>Кол-во записей</th>
            <th>Сессия</th>
            <th>Ошибка</th>
            <th>Сообщение</th>
        </tr>
        {% for harvesting_status in harvesting_status_list %}
            <tr>
                <td>{{ harvesting_status.id }}</td>
                <td>{{ harvesting_status.create_date }}</td>
                <td>{{ harvesting_status.created }}</td>
                <td>{{ harvesting_status.updated }}</td>
                <td>{{ harvesting_status.deleted }}</td>
                <td>{{ harvesting_status.processed }}</td>
                <td>{{ harvesting_status.total_records }}</td>
                <td>{{ harvesting_status.session_id }}</td>
                <td>{{ harvesting_status.error }}</td>
                <td>{{ harvesting_status.message }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

harvester/templates/harvester/index.html
{% extends 'administration/new_base.html' %}
{% block title %}Харвестер{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'harvester:index' %}">Харвестер</a></li>
{% endblock %}
{% block content %}
    {% block index_content %}
        <div class="well well-sm">
            <a class="btn btn-success btn-sm" href="{% url 'harvester:sources' %}">Источники</a>
            <a class="btn btn-success btn-sm" href="{% url 'harvester:indexing_rules' %}">Индексирование</a>
        </div>
    {% endblock %}
{% endblock %}

harvester/templates/harvester/indexing_rule_form.html
{% extends 'harvester/index.html' %}
{% load bootstrap3 %}
{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'harvester:indexing_rules' %}">Правила индексирования</a></li>
    {% if not source_file %}
        <li class="active">Добавление правила</li>
    {% else %}
        <li class="active">Редактирование правила</li>
    {% endif %}
{% endblock %}
{% block content %}
    <form method="post" novalidate>{% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-default">Сохранить</button>
    </form>
{% endblock %}

harvester/templates/harvester/indexing_rules.html
{% extends 'harvester/index.html' %}
{% block breadcrumbs %}
    {{ block.super }}
    <li class="active">Правила индексирования</li>
{% endblock %}
{% block content %}
    <div class="well well-sm">
        <a class="btn btn-success btn-sm" href="{% url 'harvester:add_indexing_rules' %}">+ Добавить правило</a>
    </div>
    <table class="table">
        <tr>
            <th>#</th>
            <th>Название</th>
            <th>Действия</th>
        </tr>
        {% for indexing_rule in indexing_rules %}
            <tr>
                <td><a href="{% url 'harvester:change_indexing_rules' indexing_rule.id %}">{{ indexing_rule.id }}</a></td>
                <td>{{ indexing_rule.name }}</td>
                <td><a href="{% url 'harvester:invoke_indexing_rule' indexing_rule.id %}">{{ indexing_rule.name }}</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

harvester/templates/harvester/records.html
{% extends 'harvester/index.html' %}
{% load bootstrap3 %}
{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'harvester:sources' %}">Источники</a></li>
    <li><a href="{% url 'harvester:source' source.id %}">{{ source.name }} ({{ source.code }})</a></li>
    <li class="active">Записи источника</li>
{% endblock %}
{% block content %}
{#    <div class="well well-sm">#}
{#    </div>#}
    <table class="table">
        <tr>
            <th>#</th>
            <th>Оригинальный id</th>
{#            <th>Формат</th>#}
{#            <th>Схема</th>#}
{#            <th>Кодировка</th>#}
{#            <th>Размер (Мб)</th>#}
{#            <th>Статус</th>#}
            <th>Сессия</th>
            <th>Удалена</th>
            <th>Дата создания</th>
            <th>Дата модификации</th>
        </tr>
        {% for record in records.object_list %}
            <tr>
                <td>{{ record.id }}</td>
                <td>{{ record.original_id }}</td>
                <td>{{ record.session_id }}</td>
                <td>{{ record.deleted }}</td>
                <td>{{ record.create_date }}</td>
                <td>{{ record.update_date }}</td>
            </tr>
        {% endfor %}
    </table>
    {% bootstrap_pagination records %}
{% endblock %}

harvester/templates/harvester/source.html
{% extends 'harvester/index.html' %}
{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'harvester:sources' %}">Источники</a></li>
    <li class="active">{{ source.name }} ({{ source.code }})</li>
{% endblock %}
{% block content %}
    <div class="well well-sm">
        <a href="{% url 'harvester:records' source.id %}" class="btn btn-success btn-sm">Записи источника</a>
        <a href="{% url 'harvester:collect_source' source.id %}" class="btn btn-success btn-sm">Пересобрать</a>
        <a href="{% url 'harvester:harvesting_status' source.id %}" class="btn btn-success btn-sm">Журнал сбора</a>
        <a href="{% url 'harvester:add_source_file' source.id %}" class="btn btn-primary btn-sm">Добавить файл</a>
        <a href="{% url 'harvester:change_source' source.id %}" class="btn btn-default btn-sm">Редактировать</a>
        <a href="{% url 'harvester:delete_source' source.id %}" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i></a>
    </div>
    <h3>Файлы</h3>
    <table class="table">
        <tr>
            <th>URI</th>
            <th>Формат</th>
            <th>Схема</th>
            <th>Кодировка</th>
            <th>Размер (Мб)</th>
            <th>Статус</th>
            <th>Дата модификации</th>
        </tr>
        {% for source_records_file in source_records_files %}
            <tr>
                <td>
                    <a href="{% url 'harvester:source_file' source.id source_records_file.id %}" title="source_records_file.file_uri">
                        {{ source_records_file.file_uri|truncatechars:50 }}
                    </a>
                </td>
                <td>{{ source_records_file.format }}</td>
                <td>{{ source_records_file.schema }}</td>
                <td>{{ source_records_file.encoding }}</td>
                <td>{{ source_records_file.get_size }}</td>
                <td>{{ source_records_file.status }}</td>
                <td>{{ source_records_file.get_update_date }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

harvester/templates/harvester/source_file.html
{% extends 'harvester/index.html' %}
{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'harvester:sources' %}">Источники</a></li>
    <li><a href="{% url 'harvester:source' source.id %}">{{ source.name }}</a></li>
    <li class="active">{{ source_records_file.file_uri }}</li>
{% endblock %}
{% block content %}
    <div class="well well-sm">
        <a href="{% url 'harvester:source_file_testing' source.id source_records_file.id %}" class="btn btn-primary btn-sm">Тестировать</a>
        <a href="{% url 'harvester:change_source_file' source.id source_records_file.id %}" class="btn btn-default btn-sm">Редактировать</a>
        <a href="{% url 'harvester:delete_source_file' source.id source_records_file.id %}" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i></a>
    </div>
    <table class="table">
        <tr>
            <th style="width: 200px">Путь к файлу</th>
            <td>{{ source_records_file.file_uri }}</td>
        </tr>
        <tr>
            <th>Дата модификации</th>
            <td>{{ source_records_file.get_update_date }}</td>
        </tr>
        <tr>
            <th>Количество записей</th>
            <td>
                <button class="btn btn-primary btn-sm" onclick="calculateRecordsCount()">Посчитать</button>
                <span class="records_count"></span>
            </td>
        </tr>
    </table>

    <script>
        function calculateRecordsCount() {
            var $recordsCountResults = $('.records_count');
            $recordsCountResults.text('ждите...');
            $.get('{% url 'harvester:calculate_records_count' source.id source_records_file.id %}').then(function (data) {
                $recordsCountResults.text(data.result);
            }).catch(function (reason) {
                $recordsCountResults.text('Ошибка при запросе');
            });
        }
    </script>
{% endblock %}

harvester/templates/harvester/source_file_form.html
{% extends 'harvester/index.html' %}
{% load bootstrap3 %}
{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'harvester:sources' %}">Источники</a></li>
    <li><a href="{% url 'harvester:source' source.id %}">{{ source.name }}</a></li>
    {% if not source_file %}
        <li class="active">Добавление файла</li>
    {% else %}
        <li><a href="{% url 'harvester:source_file' source.id source_file.id %}">{{ source_file.uri }}</a></li>
        <li class="active">Редактирование файла</li>
    {% endif %}
{% endblock %}
{% block content %}
    <form method="post" novalidate>{% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-default">Сохранить</button>
    </form>
{% endblock %}

harvester/templates/harvester/source_file_testing.html
{% extends 'harvester/index.html' %}
{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'harvester:sources' %}">Источники</a></li>
    <li><a href="{% url 'harvester:source' source.id %}">{{ source.name }}</a></li>
    <li>
        <a href="{% url 'harvester:source_file' source.id source_records_file.id %}">
            {{ source_records_file.file_uri }}
        </a>
    </li>
    <li class="active">Тестирование</li>
{% endblock %}
{% block content %}
    <div class="well well-sm">
        <form method="get">
            {{ testing_form }}
            <button type="submit">Показать запись</button>
        </form>
    </div>
    <div class="panel">
        <div class="panel-body">
            {{ record_dump|safe }}
        </div>
    </div>
{% endblock %}

harvester/templates/harvester/source_form.html
{% extends 'harvester/index.html' %}
{% load bootstrap3 %}
{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'harvester:sources' %}">Источники</a></li>
    {% if not source %}
        <li class="active">Добавление источника</li>
    {% else %}
        <li><a href="{% url 'harvester:source' source.id %}">{{ source.name }}</a></li>
        <li class="active">Редактирование</li>
    {% endif %}
{% endblock %}
{% block content %}
    <form method="post" novalidate>{% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-default">Сохранить</button>
    </form>
{% endblock %}

harvester/templates/harvester/sources.html
{% extends 'harvester/index.html' %}
{% block breadcrumbs %}
    {{ block.super }}
    <li class="active">Источники</li>
{% endblock %}
{% block content %}
    <div class="well well-sm">
        <a class="btn btn-success btn-sm" href="{% url 'harvester:add_source' %}">+ Добавить источник</a>
    </div>
    <table class="table">
        <tr>
            <th>Код</th>
            <th>Название</th>
            <th>Активен</th>
            <th>Режим сброса</th>
            <th>Дата создания</th>
        </tr>
        {% for source in sources %}
            <tr>
                <td><a href="{% url 'harvester:source' source.id %}">{{ source.code }}</a></td>
                <td>{{ source.name }}</td>
                <td>{{ source.active }}</td>
                <td>{{ source.reset }}</td>
                <td>{{ source.create_date }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}